# Generated by Django 6.1.1 on 2026-09-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_business_wastecategory_collectorprofile_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecategory',
            name='is_recyclable',
            field=models.BooleanField(default=False),
        ),
    ]
