# Generated by Django 6.1.1 on 2026-09-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wastecategory_is_recyclable'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='is_correctly_sorted',
            field=models.BooleanField(default=False),
        ),
    ]
