# Generated by Django 6.1.1 on 2026-09-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_collectionitem_is_correctly_sorted'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='successful_collection_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
